version: "2"
services:
  app:
    image: iucn/ecolex_web:latest
    container_name: ecolex_prod_app
    ports:
      - "127.0.0.1:7270:8000"
    environment:
      TZ: ${TZ}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      EDW_RUN_SOLR_URI: ${EDW_RUN_SOLR_URI}
      SOLR_HOST: ${SOLR_HOST}
      SOLR_PORT: ${SOLR_PORT}
      EDW_RUN_WEB_ECOLEX_CODE: ${EDW_RUN_WEB_ECOLEX_CODE}
      EDW_RUN_WEB_FAOLEX_API_KEY: ${EDW_RUN_WEB_FAOLEX_API_KEY}
      EDW_RUN_WEB_FAOLEX_CODE: ${EDW_RUN_WEB_FAOLEX_CODE}
      EDW_RUN_WEB_FAOLEX_CODE_2: ${EDW_RUN_WEB_FAOLEX_CODE_2}
      EDW_RUN_WEB_FAOLEX_ENABLED: ${EDW_RUN_WEB_FAOLEX_ENABLED}
      EDW_RUN_WEB_INFORMEA_CODE: ${EDW_RUN_WEB_INFORMEA_CODE}
      EDW_RUN_WEB_PORT: ${EDW_RUN_WEB_PORT}
      EDW_RUN_WEB_SECRET_KEY: ${EDW_RUN_WEB_SECRET_KEY}
      EDW_RUN_WEB_SENTRY_DSN: ${EDW_RUN_WEB_SENTRY_DSN}
      EDW_RUN_WEB_SENTRY_PUBLIC_DSN: ${EDW_RUN_WEB_SENTRY_PUBLIC_DSN}
      EDW_RUN_WEB_STATIC_ROOT: ${EDW_RUN_WEB_STATIC_ROOT}
      EDW_RUN_WEB_DEBUG: ${EDW_RUN_WEB_DEBUG}
    volumes:
      - ../www_ecolex_static:/www_static
      - ../web_logs:/home/web/ecolex/logs
    logging:
      driver: journald
    restart: "always"
