version: "2"
services:
  web:
    image: iucn/ecolex_web:latest
    container_name: ecx_web
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      TZ: Europe/Copenhagen
    env_file:
      - web.env
      - mysql.env
    # adding environment: will override any of the above.
    # letting VAR with no '=VAL' will use value from the env docker-compose is being run
    volumes_from:
      - webvolumefixer
    depends_on:
      - webvolumefixer
      - solr
      - maria
    logging:
      driver: journald
    restart: "always"

  webvolumefixer:
    image: alpine:latest
    container_name: ecx_webvolumefixer
    volumes:
      - ../www_ecolex_static:/www_static
      - ../web_logs:/home/web/ecolex/logs
    # we know user web from service web has ids 1000:1000; we control its Dockerfile
    command: ["chown", "-R", "1000:1000", "/www_static", "/home/web/ecolex/logs"]
    logging:
      driver: journald

  maria:
    image: mariadb:10
    container_name: ecx_maria
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ecolex_db_maria:/var/lib/mysql
    logging:
      driver: journald
    restart: "always"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--query-cache-size=${EDW_RUN_MARIA_query_cache_size}", "--max-allowed-packet=${EDW_RUN_MARIA_query_cache_size}",
              "--max-connections=${EDW_RUN_MARIA_max_connections}", "--max-heap-table-size=${EDW_RUN_MARIA_max_heap_table_size}", "--tmp_table_size=${EDW_RUN_MARIA_tmp_table_size}",
              "--query_cache_limit=${EDW_RUN_MARIA_query_cache_limit}", "--innodb-buffer-pool-size=${EDW_RUN_MARIA_innodb_buffer_pool_size}", "--slow-query-log=${EDW_RUN_MARIA_slow_query_log}" ,
              "--innodb-log-file-size=300M"  ]

  solr:
    image: solr:5.5 
    container_name: ecx_solr
    ports:
      - "8983:8983"
    environment:
      TZ: ${TZ}
      EDW_RUN_SOLR_HEAP_MB: ${EDW_RUN_SOLR_HEAP_MB}
      EDW_RUN_SOLR_LOG_MB: ${EDW_RUN_SOLR_LOG_MB}
    volumes:
      - ./solr/solr_scripts/:/docker-entrypoint-initdb.d/
      - ecolex_solr:/opt/solr/server/solr/mycores
      - ./solr/ecolex_initial_conf:/core-template/ecolex_initial_conf:ro
    logging:
      driver: journald
    restart: "always"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ecolex 
      - /core-template/ecolex_initial_conf

volumes:
  ecolex_solr:
    driver: local
  ecolex_db_maria:
    driver: local

