version: "2"
services:
  web:
    image: ${EDW_BUILD_DOCKERHUB}/ecolex_web:$EDW_BUILD_VER
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - deploy/common.env
      - deploy/web/docker.env
      - deploy/secret.env
    # adding environment: will override any of the above.
    # letting VAR with no '=VAL' will use value from the env docker-compose is being run
    volumes_from:
      - staticdata
    depends_on:
      - staticdata
      - solr
      - maria
    restart: "always"

  staticdata:
    image: alpine:latest
    volumes:
      - /var/local/www_ecolex_static:/www_static
    # we know user web from service web has ids 1000:1000; we control its Dockerfile
    command: ["chown", "-R", "1000:1000", "/www_static"]

  maria:
    image: ${EDW_BUILD_DOCKERHUB}/ecolex_maria:$EDW_BUILD_VER
    volumes:
      - ecolex_db_maria:/var/lib/mysql
    env_file:
      - deploy/common.env
      - deploy/maria/docker.env
      - deploy/secret.env
    restart: "always"


  solr:
    image: ${EDW_BUILD_DOCKERHUB}/ecolex_solr:$EDW_BUILD_VER
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - ecolex_solr:/opt/solr/server/solr
    env_file:
      - deploy/common.env
      - deploy/solr/docker.env
      - deploy/secret.env
    restart: "always"


volumes:
  ecolex_solr:
    driver: local
  ecolex_db_maria:
    driver: local

