solr:
    image: solr:5.5
    ports:
        - "127.0.0.1:8983:8983"
    command:
        bash -c "cp /opt/solr/bin/solr.in.sh /opt/solr/bin/solr.in.sh.orig &&
                 sed -e 's/SOLR_HEAP=".*"/SOLR_HEAP="4096m"/' </opt/solr/bin/solr.in.sh.orig >/opt/solr/bin/solr.in.sh &&
                 cp /opt/solr/server/resources/log4j.properties /opt/solr/server/resources/log4j.properties.orig &&
                 sed -e 's/log4j.appender.file.MaxFileSize=".*"/log4j.appender.file.MaxFileSize="200MB"/' </opt/solr/server/resources/log4j.properties.orig >/opt/solr/server/resources/log4j.properties &&
                 /opt/solr/bin/solr start -f -p 8983"
    volumes:
        - ./docker-volumes/solr/solr:/opt/solr/server/solr
        - ./solrconfigs:/ecolexconfigs
    restart: always

web:
    build:
        ./ecolex-prototype
    environment:
        - SOLR_URI=http://solr:8983/solr/ecolex
    ports:
        - 8000:8000
    command:
        bash -c "python /ecolex/manage.py migrate &&
                python /ecolex/manage.py loaddata /ecolex/ecolex/fixtures/initial_data.json &&
                python /ecolex/manage.py runserver 0.0.0.0:8000"
    links:
        - solr
    volumes:
        - ./ecolex-prototype/:/ecolex
    restart: always
