version: "2"
services:
  web:
    image: ${EDW_BUILD_DOCKERHUB}/ecolex_web:$EDW_BUILD_VER
    ports:
      - 8000:8000
    env_file:
      - deploy/common.env
      - deploy/web/docker.env
      - deploy/secret.env
    # adding environment: will override any of the above.
    # letting VAR with no '=VAL' will use value from the env docker-compose is being run
    depends_on:
      - solr
      - maria


  maria:
    image: mariadb:10.1
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ecolex_db_maria:/var/lib/mysql
    env_file:
      - deploy/common.env
      - deploy/secret.env


  solr:
    image: ${EDW_BUILD_DOCKERHUB}/ecolex_solr:$EDW_BUILD_VER
    ports:
      - "8983:8983"
    volumes:
      - ecolex_solr:/opt/solr/server/solr
    env_file:
      - deploy/common.env
      - deploy/solr/docker.env
      - deploy/secret.env



volumes:
  ecolex_solr:
    driver: local
  ecolex_db_maria:
    driver: local

