solr:
    image: solr
    ports:
        - 8983:8983
    command:
        /opt/solr/bin/solr start -f -p 8983
    volumes:
        - ./docker-volumes/solr/solr:/opt/solr/server/solr
        - ./solrconfigs:/ecolexconfigs

web:
    build:
        ./ecolex-prototype
    environment:
        - SOLR_URI=http://solr:8983/solr/ecolex
    ports:
        - 8000:8000
    command:
        bash -c "python /ecolex/manage.py migrate && python /ecolex/manage.py runserver 0.0.0.0:8000"
    links:
        - solr
    volumes:
        - ./ecolex-prototype/:/ecolex
