# zookeeper instance
zk:
    restart: always
    image: jplock/zookeeper:3.4.6
    ports:
        - 2181:2181
    
# three node solr setup
solr1:
    image: makuk66/docker-solr:5.2.1
    links:
        - zk
    ports:
        - 8983:8983
    command:
        /opt/solr/bin/solr start -f -z zk:2181
solr2:
    image: makuk66/docker-solr:5.2.1
    links:
        - zk
    ports:
        - 8984:8983
    command:
        /opt/solr/bin/solr start -f -z zk:2181
solr3:
    image: makuk66/docker-solr:5.2.1
    links:
        - zk
    ports:
        - 8985:8983
    command:
        /opt/solr/bin/solr start -f -z zk:2181

web:
    build:./ecolex-prototype
    ports:
        - 8000:8000
    command:
        - python manage.py runserver 0.0.0.0:8000
    links:
        - solr1
    env_file:
        - ./env
    volumes:
        - ./ecolex-prototype/:/ecolex
