#zookeeper instance
zk:
    restart: always
    image: jplock/zookeeper:3.4.6
    ports:
        - 2181:2181
    
#three node setup
solr1:
    image: makuk66/docker-solr:5.2.1
    links:
        - zk
    ports:
        - 8983:8983
    command:
        /opt/solr/bin/solr start -f -z zk:2181
solr2:
    image: makuk66/docker-solr:5.2.1
    links:
        - zk
    ports:
        - 8984:8983
    command:
        /opt/solr/bin/solr start -f -z zk:2181
solr3:
    image: makuk66/docker-solr:5.2.1
    links:
        - zk
    ports:
        - 8985:8983
    command:
        /opt/solr/bin/solr start -f -z zk:2181

