zk:
    restart: always
    image: jplock/zookeeper:3.4.6
    ports:
        - 2181:2181

solr1:
    image: makuk66/docker-solr:5.2.1
    links:
        - zk
    ports:
        - 8984:8984
    command:
        /opt/solr/bin/solr start -f -z zk:2181 -h [PUBLIC_IP] -p 8984

web:
    build:
        ./ecolex-prototype
    env_file:
        ./env
    ports:
        - 8000:8000
    command:
        bash -c "python /ecolex/manage.py treaties_cache && python /ecolex/manage.py runserver 0.0.0.0:8000"
    links:
        - solr1
    volumes:
        - ./ecolex-prototype/:/ecolex
